PRAGMA foreign_keys = ON;
CREATE TABLE organizations(id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE workspaces(id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(id),name TEXT NOT NULL,require_review INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users(id TEXT PRIMARY KEY,access_subject TEXT UNIQUE NOT NULL,email TEXT NOT NULL);
CREATE TABLE workspace_members(workspace_id TEXT NOT NULL REFERENCES workspaces(id),user_id TEXT NOT NULL REFERENCES users(id),role TEXT NOT NULL CHECK(role IN ('viewer','editor','publisher','admin')),active INTEGER NOT NULL DEFAULT 1,PRIMARY KEY(workspace_id,user_id));
CREATE TABLE ai_assets(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),type TEXT NOT NULL CHECK(type IN ('prompt','skill')),name TEXT NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',owner_user_id TEXT REFERENCES users(id),sharing_scope TEXT NOT NULL CHECK(sharing_scope IN ('private','workspace')),status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived','deleted')),latest_version INTEGER NOT NULL DEFAULT 1,tags_json TEXT NOT NULL DEFAULT '[]',created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,type,name));
CREATE INDEX idx_assets ON ai_assets(workspace_id,status,updated_at DESC);
CREATE TABLE ai_asset_versions(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL REFERENCES ai_assets(id),version INTEGER NOT NULL,definition_json TEXT NOT NULL CHECK(json_valid(definition_json)),definition_hash TEXT NOT NULL,notes TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(asset_id,version),UNIQUE(asset_id,definition_hash),UNIQUE(asset_id,version));
CREATE TABLE version_write_guards(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL REFERENCES ai_assets(id),expected_latest_version INTEGER NOT NULL);
CREATE TRIGGER version_guard BEFORE INSERT ON version_write_guards BEGIN SELECT CASE WHEN (SELECT latest_version FROM ai_assets WHERE id=NEW.asset_id)<>NEW.expected_latest_version THEN RAISE(ABORT,'version_conflict') END; END;
CREATE TRIGGER version_sequence BEFORE INSERT ON ai_asset_versions WHEN NEW.version>1 BEGIN
 SELECT CASE WHEN (SELECT latest_version FROM ai_assets WHERE id=NEW.asset_id)<>NEW.version THEN RAISE(ABORT,'version_conflict') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM version_write_guards WHERE asset_id=NEW.asset_id AND expected_latest_version=NEW.version-1) THEN RAISE(ABORT,'version_guard_required') END;
END;
CREATE TRIGGER version_immutable_update BEFORE UPDATE ON ai_asset_versions BEGIN SELECT RAISE(ABORT,'immutable_version'); END;
CREATE TRIGGER version_immutable_delete BEFORE DELETE ON ai_asset_versions BEGIN SELECT RAISE(ABORT,'immutable_version'); END;
CREATE TABLE ai_asset_aliases(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL REFERENCES ai_assets(id),alias TEXT NOT NULL CHECK(alias IN ('staging','production')),version INTEGER NOT NULL,revision INTEGER NOT NULL DEFAULT 1,reason TEXT,action TEXT NOT NULL CHECK(action IN ('stage','publish','rollback')),moved_by TEXT NOT NULL REFERENCES users(id),moved_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(asset_id,alias),FOREIGN KEY(asset_id,version) REFERENCES ai_asset_versions(asset_id,version));
CREATE TABLE alias_write_guards(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL REFERENCES ai_assets(id),alias TEXT NOT NULL,expected_revision INTEGER NOT NULL);
CREATE TRIGGER alias_guard BEFORE INSERT ON alias_write_guards BEGIN
 SELECT CASE WHEN COALESCE((SELECT revision FROM ai_asset_aliases WHERE asset_id=NEW.asset_id AND alias=NEW.alias),0)<>NEW.expected_revision THEN RAISE(ABORT,'alias_conflict') END;
END;
CREATE TABLE ai_asset_test_cases(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL REFERENCES ai_assets(id),name TEXT NOT NULL,input_json TEXT NOT NULL DEFAULT '{}',expected_output_json TEXT,evaluator_json TEXT NOT NULL DEFAULT '{}',required_for_production INTEGER NOT NULL DEFAULT 0,case_revision INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(asset_id,name));
CREATE TABLE ai_asset_test_runs(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL REFERENCES ai_assets(id),version INTEGER NOT NULL,test_case_id TEXT REFERENCES ai_asset_test_cases(id),case_revision INTEGER,status TEXT NOT NULL CHECK(status IN ('passed','failed','error','not_evaluated')),input_hash TEXT,output_hash TEXT,model TEXT,run_by TEXT REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(asset_id,version) REFERENCES ai_asset_versions(asset_id,version));
CREATE TABLE ai_asset_reviews(id TEXT PRIMARY KEY,asset_id TEXT NOT NULL REFERENCES ai_assets(id),version INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected')),requested_by TEXT NOT NULL REFERENCES users(id),reviewed_by TEXT REFERENCES users(id),comment TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(asset_id,version) REFERENCES ai_asset_versions(asset_id,version));
CREATE TABLE ai_asset_audit_logs(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),actor_id TEXT,event_type TEXT NOT NULL,asset_id TEXT,version INTEGER,before_json TEXT,after_json TEXT,reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_audit ON ai_asset_audit_logs(workspace_id,created_at DESC);
CREATE TRIGGER audit_immutable_update BEFORE UPDATE ON ai_asset_audit_logs BEGIN SELECT RAISE(ABORT,'immutable_audit'); END;
CREATE TRIGGER audit_immutable_delete BEFORE DELETE ON ai_asset_audit_logs BEGIN SELECT RAISE(ABORT,'immutable_audit'); END;
CREATE TABLE ai_asset_executions(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),asset_id TEXT NOT NULL REFERENCES ai_assets(id),requested_ref TEXT NOT NULL,resolved_version INTEGER NOT NULL,definition_hash TEXT NOT NULL,trace_id TEXT NOT NULL UNIQUE,caller_app TEXT,environment TEXT,model TEXT,status TEXT NOT NULL CHECK(status IN ('resolved','success','failure')),latency_ms INTEGER,cost_usd TEXT,input_hash TEXT,output_hash TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_executions ON ai_asset_executions(workspace_id,created_at DESC);
CREATE TABLE service_tokens(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),name TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,scopes_json TEXT NOT NULL,created_by TEXT NOT NULL REFERENCES users(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,expires_at TEXT,revoked_at TEXT);
CREATE TABLE webhook_endpoints(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),url TEXT NOT NULL,encrypted_secret TEXT NOT NULL,events_json TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE event_outbox(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),event_type TEXT NOT NULL,payload_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,next_attempt_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_outbox ON event_outbox(status,next_attempt_at);
CREATE TABLE webhook_deliveries(id TEXT PRIMARY KEY,event_id TEXT NOT NULL REFERENCES event_outbox(id),endpoint_id TEXT NOT NULL REFERENCES webhook_endpoints(id),status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,next_attempt_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,leased_until TEXT,delivered_at TEXT,last_response_code INTEGER,UNIQUE(event_id,endpoint_id));
CREATE INDEX idx_deliveries ON webhook_deliveries(status,next_attempt_at);
CREATE TABLE idempotency_keys(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL,actor_id TEXT NOT NULL,method TEXT NOT NULL,path TEXT NOT NULL,idem_key TEXT NOT NULL,request_hash TEXT NOT NULL,response_status INTEGER,response_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(workspace_id,actor_id,method,path,idem_key));
CREATE TABLE skill_files(asset_id TEXT NOT NULL,version INTEGER NOT NULL,filename TEXT NOT NULL,r2_key TEXT NOT NULL,sha256 TEXT NOT NULL,size_bytes INTEGER NOT NULL,mime TEXT NOT NULL,PRIMARY KEY(asset_id,version,filename),FOREIGN KEY(asset_id,version) REFERENCES ai_asset_versions(asset_id,version));
CREATE TRIGGER policy_alias_insert BEFORE INSERT ON ai_asset_aliases BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ai_assets a JOIN workspace_members m ON m.workspace_id=a.workspace_id WHERE a.id=NEW.asset_id AND a.status='active' AND m.user_id=NEW.moved_by AND m.active=1 AND (m.role IN ('publisher','admin') OR (NEW.alias='staging' AND m.role='editor'))) THEN RAISE(ABORT,'permission_denied') END;
 SELECT CASE WHEN NEW.alias='production' AND (NEW.reason IS NULL OR trim(NEW.reason)='') THEN RAISE(ABORT,'reason_required') END;
 SELECT CASE WHEN NEW.alias='production' AND EXISTS(SELECT 1 FROM ai_asset_test_cases c WHERE c.asset_id=NEW.asset_id AND c.required_for_production=1 AND NOT EXISTS(SELECT 1 FROM ai_asset_test_runs r WHERE r.asset_id=NEW.asset_id AND r.version=NEW.version AND r.test_case_id=c.id AND r.case_revision=c.case_revision AND r.status='passed' AND r.created_at=(SELECT MAX(created_at) FROM ai_asset_test_runs WHERE test_case_id=c.id AND version=NEW.version))) THEN RAISE(ABORT,'test_required') END;
 SELECT CASE WHEN NEW.alias='production' AND EXISTS(SELECT 1 FROM ai_assets a JOIN workspaces w ON w.id=a.workspace_id WHERE a.id=NEW.asset_id AND w.require_review=1 AND NOT EXISTS(SELECT 1 FROM ai_asset_reviews r JOIN ai_asset_versions v ON v.asset_id=r.asset_id AND v.version=r.version WHERE r.asset_id=a.id AND r.version=NEW.version AND r.status='approved' AND r.reviewed_by<>v.created_by)) THEN RAISE(ABORT,'review_required') END;
END;
CREATE TRIGGER policy_alias_update BEFORE UPDATE ON ai_asset_aliases BEGIN
 SELECT CASE WHEN NEW.revision<>OLD.revision+1 THEN RAISE(ABORT,'alias_conflict') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ai_assets a JOIN workspace_members m ON m.workspace_id=a.workspace_id WHERE a.id=NEW.asset_id AND a.status='active' AND m.user_id=NEW.moved_by AND m.active=1 AND (m.role IN ('publisher','admin') OR (NEW.alias='staging' AND m.role='editor'))) THEN RAISE(ABORT,'permission_denied') END;
 SELECT CASE WHEN NEW.alias='production' AND (NEW.reason IS NULL OR trim(NEW.reason)='') THEN RAISE(ABORT,'reason_required') END;
 SELECT CASE WHEN NEW.alias='production' AND EXISTS(SELECT 1 FROM ai_asset_test_cases c WHERE c.asset_id=NEW.asset_id AND c.required_for_production=1 AND NOT EXISTS(SELECT 1 FROM ai_asset_test_runs r WHERE r.asset_id=NEW.asset_id AND r.version=NEW.version AND r.test_case_id=c.id AND r.case_revision=c.case_revision AND r.status='passed' AND r.created_at=(SELECT MAX(created_at) FROM ai_asset_test_runs WHERE test_case_id=c.id AND version=NEW.version))) THEN RAISE(ABORT,'test_required') END;
 SELECT CASE WHEN NEW.alias='production' AND EXISTS(SELECT 1 FROM ai_assets a JOIN workspaces w ON w.id=a.workspace_id WHERE a.id=NEW.asset_id AND w.require_review=1 AND NOT EXISTS(SELECT 1 FROM ai_asset_reviews r JOIN ai_asset_versions v ON v.asset_id=r.asset_id AND v.version=r.version WHERE r.asset_id=a.id AND r.version=NEW.version AND r.status='approved' AND r.reviewed_by<>v.created_by)) THEN RAISE(ABORT,'review_required') END;
END;
CREATE TRIGGER version_audit AFTER INSERT ON ai_asset_versions BEGIN
 INSERT INTO ai_asset_audit_logs(id,workspace_id,actor_id,event_type,asset_id,version,after_json) SELECT lower(hex(randomblob(16))),a.workspace_id,NEW.created_by,'asset.version_created',NEW.asset_id,NEW.version,json_object('hash',NEW.definition_hash) FROM ai_assets a WHERE a.id=NEW.asset_id;
 INSERT INTO event_outbox(id,workspace_id,event_type,payload_json) SELECT lower(hex(randomblob(16))),a.workspace_id,'asset.version_created',json_object('asset_id',NEW.asset_id,'version',NEW.version,'hash',NEW.definition_hash) FROM ai_assets a WHERE a.id=NEW.asset_id;
END;
CREATE TRIGGER alias_audit_insert AFTER INSERT ON ai_asset_aliases BEGIN
 INSERT INTO ai_asset_audit_logs(id,workspace_id,actor_id,event_type,asset_id,version,after_json,reason) SELECT lower(hex(randomblob(16))),a.workspace_id,NEW.moved_by,CASE WHEN NEW.action='rollback' THEN 'asset.rollback' WHEN NEW.alias='production' THEN 'asset.published' ELSE 'asset.alias_moved' END,NEW.asset_id,NEW.version,json_object('alias',NEW.alias,'revision',NEW.revision),NEW.reason FROM ai_assets a WHERE a.id=NEW.asset_id;
 INSERT INTO event_outbox(id,workspace_id,event_type,payload_json) SELECT lower(hex(randomblob(16))),a.workspace_id,CASE WHEN NEW.action='rollback' THEN 'asset.rollback' WHEN NEW.alias='production' THEN 'asset.published' ELSE 'asset.alias_moved' END,json_object('asset_id',NEW.asset_id,'alias',NEW.alias,'version',NEW.version,'revision',NEW.revision) FROM ai_assets a WHERE a.id=NEW.asset_id;
END;
CREATE TRIGGER alias_audit_update AFTER UPDATE ON ai_asset_aliases BEGIN
 INSERT INTO ai_asset_audit_logs(id,workspace_id,actor_id,event_type,asset_id,version,before_json,after_json,reason) SELECT lower(hex(randomblob(16))),a.workspace_id,NEW.moved_by,CASE WHEN NEW.action='rollback' THEN 'asset.rollback' WHEN NEW.alias='production' THEN 'asset.published' ELSE 'asset.alias_moved' END,NEW.asset_id,NEW.version,json_object('version',OLD.version),json_object('alias',NEW.alias,'revision',NEW.revision),NEW.reason FROM ai_assets a WHERE a.id=NEW.asset_id;
 INSERT INTO event_outbox(id,workspace_id,event_type,payload_json) SELECT lower(hex(randomblob(16))),a.workspace_id,CASE WHEN NEW.action='rollback' THEN 'asset.rollback' WHEN NEW.alias='production' THEN 'asset.published' ELSE 'asset.alias_moved' END,json_object('asset_id',NEW.asset_id,'alias',NEW.alias,'version',NEW.version,'revision',NEW.revision) FROM ai_assets a WHERE a.id=NEW.asset_id;
END;
